env:
  node: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  NodeJS: true

ignorePatterns:
  - '!.*'
  - '!bootstrap/**'
  - '**/node_modules/.*'
  - '*.json'

extends:
  - eslint:recommended
  - plugin:github/recommended

rules:
  {
    'camelcase': 'off',
    'eslint-comments/no-use': 'off',
    'eslint-comments/no-unused-disable': 'off',
    'i18n-text/no-en': 'off',
    'import/no-namespace': 'off',
    'no-console': 'off',
    'no-unused-vars': 'off',
    'prettier/prettier': 'error',
    'semi': 'off',
    'import/extensions': 'off'
  }

parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  requireConfigFile: false